name: Doxygen
on:
  push:
    paths:
      - '**/moreinttypes.pc'
permissions:
  contents: read
jobs:
  doxygen:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false
      - name: Build docs
        run: |
         sudo apt-get -qqy install doxygen
         cd doxygen
         export DOXYGEN_PROJECT_NUMBER=$(awk '/^.*[0-9]\./{print $2}' ../pkgconfig/moreinttypes.pc)
         doxygen -u Doxyfile >/dev/null 2>&1
         doxygen Doxyfile html
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: './docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
