name: GCC,Clang
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
permissions:
  contents: read
env:
  CONFIG: '-DCMAKE_BUILD_TYPE=Debug -DMOREINTTYPES_BUILD_STATIC=ON -DMOREINTTYPES_BUILD_EXAMPLES=ON'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26-intel, macos-26]
        ubsan: ['ON', '']
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      with:
        persist-credentials: false
    - name: Configure CMake
      run: cmake -H. -B_build $CONFIG -DMOREINTTYPES_ENABLE_UBSAN=$WITH_UBSAN
      env:
        WITH_UBSAN: ${{matrix.ubsan}}
    - name: Build and Test (${{matrix.os}})
      run: cmake --build _build
