name: GCC,Clang
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
env:
  CONFIG: '-DCMAKE_BUILD_TYPE=Debug -DMOREINTTYPES_BUILD_STATIC=ON'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cmake: ['3.13', 'latest']
        ubsan: ['ON', '']
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake }}
    - name: Configure CMake
      run: cmake -H. -B_build ${{env.CONFIG}} -DMOREINTTYPES_ENABLE_UBSAN=${{matrix.ubsan}}
    - name: Build and Test (${{matrix.os}})
      run: cmake --build _build
