name: MinGW
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
permissions:
  contents: read
env:
  # FIXME:
  # ~/libmoreinttypes/test/check/lib/clock_gettime.c:35:5: error: redefinition of 'clock_gettime'
  #  35 | int clock_gettime(clockid_t clk_id CK_ATTRIBUTE_UNUSED, struct timespec *ts)
  #     |     ^
  # /usr/lib/mingw-w64/winpthreads/include/pthread_time.h:112:35: note: previous definition is here
  # 112 | WINPTHREAD_CLOCK_DECL int __cdecl clock_gettime(clockid_t clock_id, struct timespec *tp)
  #     |                                   ^
  CMAKE_CONFIG: '-DCMAKE_BUILD_TYPE=Debug -DMOREINTTYPES_BUILD_TESTS=OFF -DMOREINTTYPES_BUILD_STATIC=ON'
jobs:
  build:
    strategy:
      matrix:
        include:
          - { msystem: mingw64, arch: x86_64 }
          - { msystem: mingw32, arch: i686 }
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      with:
        persist-credentials: false
    # https://github.com/msys2/setup-msys2/blob/main/examples/cmake.yml
    - name: Set up MinGW toolchain
      uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # 2.32.0
      with:
        msystem: ${{matrix.msystem}}
        update: false
        install: |
          git
          mingw-w64-${{matrix.arch}}-toolchain
          mingw-w64-${{matrix.arch}}-cmake
    - name: Build and Test (${{matrix.msystem}})
      run: |
        cmake -H. -B_build -G"MinGW Makefiles" $CMAKE_CONFIG
        cmake --build _build
