name: MSVC
on:
  pull_request:
    branches:
      - 'ma**'
  push:
    branches:
      - 'ma**'
    tags-ignore:
      - '**'
env:
  CONFIG: '-DCMAKE_BUILD_TYPE=Debug -DBUILD_STATIC=ON'
  GENERATOR: '-G"NMake Makefiles"'
jobs:
  build:
    strategy:
      matrix:
        arch: [x86, x64]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.13.x'
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}
    - name: Configure CMake
      run: cmake -H$(pwd) -B_build ${{env.CONFIG}} ${{env.GENERATOR}}
      shell: powershell
    - name: Build and Test (msvc ${{matrix.arch}})
      run: cmake --build _build
